name: fshare
description: A simple file sharing command line app
version: 0.0.1
repository: https://github.com/HosamHasanRamadan/fshare

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  intranet_ip: ^1.0.2
  qr: ^3.0.1
  shelf_plus: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4

executables:
  fshare:
