name: fshare
description: A simple file sharing command line app
version: 0.0.5
repository: https://github.com/HosamHasanRamadan/fshare

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  intranet_ip: ^1.0.2
  qr: ^3.0.1
  shelf_plus: ^1.7.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5

executables:
  fshare:
